---
- name: configure k8s nodes
  hosts: all
  become: yes
  tasks:
    - name: create kube user
      user:
        name: kube
        state: present
    - name: create /etc/modules-load.d/containerd.conf
      file: 
        path: /etc/modules-load.d/containerd.conf
        state: touch
    - name: set containerd.conf kernel modules
      copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
                overlay
                br_netfilter
    - name: run modprobe to activate new modules
      command: modprobe overlay br_netfilter
    - name: create etc/sysctl.d/99-kubernetes-cri.conf
      file:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        state: touch
    - name: copy kubernetes-cri settings
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1
    - name: rerun sysctl to pick up changes
      command: sysctl --system
    - name: add docker-ce repo for containerd package
      yum_repository:
        name: docker-ce
        description: docker-ce repo
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable 
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes
    - name: install containerd
      yum:
        name: containerd.io
        state: present
    - name: create /etc/containerd directory
      file:
        path: /etc/containerd
        state: directory
    - name: create /etc/containerd.config.toml
      file:
        path: /etc/containerd.config.toml
        state: touch
    - name: create containerd default config
      command: "containerd config default"
      register: containerd_config   
    - name: copy containerd config to file
      template:
        src: ./containerd_config.j2
        dest: /etc/containerd.config.toml
    - name: restart containerd
      service:
        name: containerd
        state: started
        enabled: yes
    - name: turn off swap
      command: swapoff -a
    - name: configure k8s repository
      template:
        src: repo_config.j2
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: intall kubeadm cluster packages
      yum:
        name: "{{ item }}"
        state: present
      loop: 
            - kubelet
            - kubeadm
            - kubectl
    - name: start and enable kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
- name: create cluster control node
  hosts: controlplane
  become: yes
  tasks:
    - name: initialize cluster
      command: kubeadm init --pod-network-cidr 192.168.0.0/16
    - name: create .kube dir in user home
      file:
        path: /home/kube/.kube
        state: directory
        owner: kube
        group: kube
    - name: copy kubernetes admin conf to .kube
      copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/kube/.kube/config
       owner: kube
       group: kube
       remote_src: true
    - name: install calico networking plugin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    - name: create new cluster token
      command: kubeadm token create --print-join-command
      register: cluster_token
    - name: set token variable for access on node hosts
      set_fact:
        join_command = "{{ cluster_token }}"
- name: join nodes to cluster
  hosts: nodes
  become: yes
  tasks:
    - name: run cluster join command
      command: "{{ join_command }}"
